spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/iotplatform?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=round
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

server: 
  port: 8080
  
mybatis: 
  configuration: 
    mapUnderscoreToCamelCase: true
  
baseUrl: http://localhost:8545/